// The app's icons by name: the sidebar's feature list (data only) names them, the renderer draws them.

export type IconName =
  | 'dashboard'
  | 'spells'
  | 'triggers'
  | 'overlays'
  | 'audio'
  | 'logs'
  | 'settings'
  | 'play'
  | 'stop'
  | 'move'
  | 'mute'
  | 'plus'
  | 'motes'
  | 'upgrade'
  | 'trophy'
  | 'stats'
  | 'bag'
  | 'sparkle'
  | 'meter'
  | 'flag'
  | 'check'
  | 'copy'
  | 'back'
  | 'flask'
  | 'respawn'
  | 'loot'
  | 'link'
  | 'sources'
  | 'pin'
  | 'unlock'
